#!/bin/bash
set -e

# ============================================================
#  CareerBot — AWS EC2 Deployment Script (SQLite edition)
#  Run once on a fresh Ubuntu EC2 instance:
#    chmod +x deploy.sh && ./deploy.sh
#
#  Required env var (set before running):
#    export GEMINI_API_KEY=AIza...
# ============================================================

# --------------------
# 1. System packages
# --------------------
echo ""
echo "🔄 Updating system packages..."
sudo apt-get update -y && sudo apt-get upgrade -y

echo "📦 Installing Node.js 20, Nginx, Git..."
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs nginx git

echo "📦 Installing PM2 globally..."
sudo npm install -g pm2

# --------------------
# 2. Clone or pull repo
# --------------------
REPO_URL="https://github.com/DEEPAK-310705/Carreer-Chatbot.git"
APP_DIR="$HOME/Carreer-Chatbot"

echo ""
echo "📂 Setting up repository..."
if [ ! -d "$APP_DIR" ]; then
  git clone "$REPO_URL" "$APP_DIR"
else
  echo "  Repository already exists — pulling latest..."
  cd "$APP_DIR"
  git pull origin main || git pull origin master
fi

cd "$APP_DIR"

# --------------------
# 3. Install dependencies
# --------------------
echo ""
echo "📦 Installing root (frontend) packages..."
npm install

echo "📦 Installing server packages..."
cd server
npm install
cd ..

# --------------------
# 4. Build frontend
# --------------------
echo ""
echo "🏗️  Building frontend (React/Vite)..."
npm run build

# --------------------
# 5. Write server .env
# --------------------
echo ""
echo "⚙️  Writing server/.env..."

if [ -z "$GEMINI_API_KEY" ]; then
  echo "❌ Error: GEMINI_API_KEY is not set."
  echo "   Run: export GEMINI_API_KEY=AIza... then re-run this script."
  exit 1
fi

cat > server/.env <<EOF
# CareerBot Server — auto-generated by deploy.sh
GEMINI_API_KEY=${GEMINI_API_KEY}
PORT=3001
NODE_ENV=production
EOF

echo "  ✅ server/.env written."

# --------------------
# 6. Ensure DB directory is writable
# --------------------
echo ""
echo "🗄️  Ensuring SQLite database file is writable..."
touch server/careerbot.db
chmod 664 server/careerbot.db
echo "  ✅ server/careerbot.db ready."

# --------------------
# 7. Start / restart with PM2
# --------------------
echo ""
echo "🚀 Starting server with PM2..."
cd server

pm2 stop careerbot 2>/dev/null || true
pm2 delete careerbot 2>/dev/null || true

pm2 start server.js \
  --name "careerbot" \
  --node-args="--experimental-vm-modules" \
  --env production

pm2 save
pm2 startup | tail -1 | sudo bash || true

cd ..

# --------------------
# 8. Configure Nginx
# --------------------
echo ""
echo "🌐 Configuring Nginx reverse proxy..."

sudo tee /etc/nginx/sites-available/careerbot > /dev/null <<'NGINXCONF'
server {
    listen 80;
    server_name _;

    # Increase body size limit for resume uploads
    client_max_body_size 5M;

    location / {
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
}
NGINXCONF

# Enable the site
sudo ln -sf /etc/nginx/sites-available/careerbot /etc/nginx/sites-enabled/careerbot
sudo rm -f /etc/nginx/sites-enabled/default

sudo nginx -t
sudo systemctl restart nginx
sudo systemctl enable nginx

# --------------------
# 9. Done
# --------------------
echo ""
echo "============================================================"
echo "✅  CareerBot deployed successfully!"
echo ""
echo "   App is running at:  http://$(curl -s ifconfig.me)"
echo "   PM2 status:         pm2 status"
echo "   PM2 logs:           pm2 logs careerbot"
echo "   Nginx logs:         sudo tail -f /var/log/nginx/error.log"
echo "   SQLite DB:          ~/Carreer-Chatbot/server/careerbot.db"
echo "============================================================"
echo ""
